/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminDashboardRouteImport } from './routes/_admin.dashboard'
import { Route as AdminActivityLogsRouteImport } from './routes/_admin.activity-logs'
import { Route as AdminSplatRouteImport } from './routes/_admin.$'
import { Route as AdminSchoolsIndexRouteImport } from './routes/_admin.schools.index'
import { Route as AdminReportsIndexRouteImport } from './routes/_admin.reports.index'
import { Route as AdminOrdersIndexRouteImport } from './routes/_admin.orders.index'
import { Route as AdminDashboardIndexRouteImport } from './routes/_admin.dashboard.index'
import { Route as AdminCustomersIndexRouteImport } from './routes/_admin.customers.index'
import { Route as AdminBunchIndexRouteImport } from './routes/_admin.bunch.index'
import { Route as AdminBooksIndexRouteImport } from './routes/_admin.books.index'
import { Route as PrintLabelIdRouteImport } from './routes/print.label.$id'
import { Route as PrintInvoiceIdRouteImport } from './routes/print.invoice.$id'
import { Route as AdminUsersStaffPermissionsRouteImport } from './routes/_admin.users.staff-permissions'
import { Route as AdminUsersStaffRouteImport } from './routes/_admin.users.staff'
import { Route as AdminUsersMenusRouteImport } from './routes/_admin.users.menus'
import { Route as AdminUsersDesignationsRouteImport } from './routes/_admin.users.designations'
import { Route as AdminUsersDesignationPermissionsRouteImport } from './routes/_admin.users.designation-permissions'
import { Route as AdminShippingZonesRouteImport } from './routes/_admin.shipping.zones'
import { Route as AdminShippingTrackingRouteImport } from './routes/_admin.shipping.tracking'
import { Route as AdminShippingShipmentsRouteImport } from './routes/_admin.shipping.shipments'
import { Route as AdminShippingRulesRouteImport } from './routes/_admin.shipping.rules'
import { Route as AdminShippingReturnPickupRouteImport } from './routes/_admin.shipping.return-pickup'
import { Route as AdminShippingPickupRouteImport } from './routes/_admin.shipping.pickup'
import { Route as AdminShippingNdrRouteImport } from './routes/_admin.shipping.ndr'
import { Route as AdminShippingLabelsRouteImport } from './routes/_admin.shipping.labels'
import { Route as AdminShippingEtaRouteImport } from './routes/_admin.shipping.eta'
import { Route as AdminShippingCouriersRouteImport } from './routes/_admin.shipping.couriers'
import { Route as AdminShippingChargesRouteImport } from './routes/_admin.shipping.charges'
import { Route as AdminShippingAwbRouteImport } from './routes/_admin.shipping.awb'
import { Route as AdminSettingsThemeRouteImport } from './routes/_admin.settings.theme'
import { Route as AdminSettingsStoreRouteImport } from './routes/_admin.settings.store'
import { Route as AdminSettingsSmsRouteImport } from './routes/_admin.settings.sms'
import { Route as AdminSettingsShippingRouteImport } from './routes/_admin.settings.shipping'
import { Route as AdminSettingsPaymentsRouteImport } from './routes/_admin.settings.payments'
import { Route as AdminSettingsPagesRouteImport } from './routes/_admin.settings.pages'
import { Route as AdminSettingsNotificationsRouteImport } from './routes/_admin.settings.notifications'
import { Route as AdminSettingsMaintenanceRouteImport } from './routes/_admin.settings.maintenance'
import { Route as AdminSettingsLogsRouteImport } from './routes/_admin.settings.logs'
import { Route as AdminSettingsGstRouteImport } from './routes/_admin.settings.gst'
import { Route as AdminSettingsGeneralRouteImport } from './routes/_admin.settings.general'
import { Route as AdminSettingsEmailRouteImport } from './routes/_admin.settings.email'
import { Route as AdminSettingsCurrencyRouteImport } from './routes/_admin.settings.currency'
import { Route as AdminSettingsCompanyRouteImport } from './routes/_admin.settings.company'
import { Route as AdminSettingsBackupRouteImport } from './routes/_admin.settings.backup'
import { Route as AdminSchoolsClassesRouteImport } from './routes/_admin.schools.classes'
import { Route as AdminReportsSalesRouteImport } from './routes/_admin.reports.sales'
import { Route as AdminReportsRevenueRouteImport } from './routes/_admin.reports.revenue'
import { Route as AdminReportsInventoryRouteImport } from './routes/_admin.reports.inventory'
import { Route as AdminPaymentsRefundsRouteImport } from './routes/_admin.payments.refunds'
import { Route as AdminPaymentsCodRouteImport } from './routes/_admin.payments.cod'
import { Route as AdminOrdersReturnsRouteImport } from './routes/_admin.orders.returns'
import { Route as AdminOrdersRefundsRouteImport } from './routes/_admin.orders.refunds'
import { Route as AdminOrdersProcessingRouteImport } from './routes/_admin.orders.processing'
import { Route as AdminOrdersExchangesRouteImport } from './routes/_admin.orders.exchanges'
import { Route as AdminOrdersCancellationsRouteImport } from './routes/_admin.orders.cancellations'
import { Route as AdminMarketingCouponsRouteImport } from './routes/_admin.marketing.coupons'
import { Route as AdminLocaleTimezonesRouteImport } from './routes/_admin.locale.timezones'
import { Route as AdminLocaleStatesRouteImport } from './routes/_admin.locale.states'
import { Route as AdminLocaleLanguagesRouteImport } from './routes/_admin.locale.languages'
import { Route as AdminLocaleCurrenciesRouteImport } from './routes/_admin.locale.currencies'
import { Route as AdminLocaleCountriesRouteImport } from './routes/_admin.locale.countries'
import { Route as AdminLocaleCitiesRouteImport } from './routes/_admin.locale.cities'
import { Route as AdminInventoryWarehousesRouteImport } from './routes/_admin.inventory.warehouses'
import { Route as AdminInventoryStockRouteImport } from './routes/_admin.inventory.stock'
import { Route as AdminInventoryMultiWarehouseRouteImport } from './routes/_admin.inventory.multi-warehouse'
import { Route as AdminInventoryBarcodeRouteImport } from './routes/_admin.inventory.barcode'
import { Route as AdminIntegrationsWhatsappRouteImport } from './routes/_admin.integrations.whatsapp'
import { Route as AdminIntegrationsWebhooksRouteImport } from './routes/_admin.integrations.webhooks'
import { Route as AdminIntegrationsSmsRouteImport } from './routes/_admin.integrations.sms'
import { Route as AdminIntegrationsPixelRouteImport } from './routes/_admin.integrations.pixel'
import { Route as AdminIntegrationsPaymentRouteImport } from './routes/_admin.integrations.payment'
import { Route as AdminIntegrationsGtmRouteImport } from './routes/_admin.integrations.gtm'
import { Route as AdminIntegrationsEmailRouteImport } from './routes/_admin.integrations.email'
import { Route as AdminIntegrationsCourierRouteImport } from './routes/_admin.integrations.courier'
import { Route as AdminIntegrationsAnalyticsRouteImport } from './routes/_admin.integrations.analytics'
import { Route as AdminIntegrationsAccountingRouteImport } from './routes/_admin.integrations.accounting'
import { Route as AdminDashboardProductAnalyticsRouteImport } from './routes/_admin.dashboard.product-analytics'
import { Route as AdminDashboardOrderAnalysisRouteImport } from './routes/_admin.dashboard.order-analysis'
import { Route as AdminCustomersWishlistRouteImport } from './routes/_admin.customers.wishlist'
import { Route as AdminCustomersTicketsRouteImport } from './routes/_admin.customers.tickets'
import { Route as AdminCustomersReviewsRouteImport } from './routes/_admin.customers.reviews'
import { Route as AdminCmsFaqRouteImport } from './routes/_admin.cms.faq'
import { Route as AdminCmsBlogRouteImport } from './routes/_admin.cms.blog'
import { Route as AdminCmsBannersRouteImport } from './routes/_admin.cms.banners'
import { Route as AdminCatalogSuppliersRouteImport } from './routes/_admin.catalog.suppliers'
import { Route as AdminCatalogSubjectsRouteImport } from './routes/_admin.catalog.subjects'
import { Route as AdminCatalogSubcategoriesRouteImport } from './routes/_admin.catalog.subcategories'
import { Route as AdminCatalogSeriesRouteImport } from './routes/_admin.catalog.series'
import { Route as AdminCatalogPublishersRouteImport } from './routes/_admin.catalog.publishers'
import { Route as AdminCatalogLanguagesRouteImport } from './routes/_admin.catalog.languages'
import { Route as AdminCatalogGenresRouteImport } from './routes/_admin.catalog.genres'
import { Route as AdminCatalogFormatsRouteImport } from './routes/_admin.catalog.formats'
import { Route as AdminCatalogEditionsRouteImport } from './routes/_admin.catalog.editions'
import { Route as AdminCatalogCategoriesRouteImport } from './routes/_admin.catalog.categories'
import { Route as AdminCatalogBrandsRouteImport } from './routes/_admin.catalog.brands'
import { Route as AdminCatalogBoardsRouteImport } from './routes/_admin.catalog.boards'
import { Route as AdminCatalogAuthorsRouteImport } from './routes/_admin.catalog.authors'
import { Route as AdminBunchReturnsRouteImport } from './routes/_admin.bunch.returns'
import { Route as AdminBunchOrdersRouteImport } from './routes/_admin.bunch.orders'
import { Route as AdminBunchOrderAnalysisRouteImport } from './routes/_admin.bunch.order-analysis'
import { Route as AdminBunchExchangesRouteImport } from './routes/_admin.bunch.exchanges'
import { Route as AdminBooksImportExportRouteImport } from './routes/_admin.books.import-export'
import { Route as AdminBooksBulkUploadRouteImport } from './routes/_admin.books.bulk-upload'
import { Route as AdminBooksBulkUpdateRouteImport } from './routes/_admin.books.bulk-update'
import { Route as AdminPaymentsTransactionsIndexRouteImport } from './routes/_admin.payments.transactions.index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActivityLogsRoute = AdminActivityLogsRouteImport.update({
  id: '/activity-logs',
  path: '/activity-logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSplatRoute = AdminSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSchoolsIndexRoute = AdminSchoolsIndexRouteImport.update({
  id: '/schools/',
  path: '/schools/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsIndexRoute = AdminReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersIndexRoute = AdminOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardIndexRoute = AdminDashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminDashboardRoute,
} as any)
const AdminCustomersIndexRoute = AdminCustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBunchIndexRoute = AdminBunchIndexRouteImport.update({
  id: '/bunch/',
  path: '/bunch/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBooksIndexRoute = AdminBooksIndexRouteImport.update({
  id: '/books/',
  path: '/books/',
  getParentRoute: () => AdminRoute,
} as any)
const PrintLabelIdRoute = PrintLabelIdRouteImport.update({
  id: '/print/label/$id',
  path: '/print/label/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PrintInvoiceIdRoute = PrintInvoiceIdRouteImport.update({
  id: '/print/invoice/$id',
  path: '/print/invoice/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersStaffPermissionsRoute =
  AdminUsersStaffPermissionsRouteImport.update({
    id: '/users/staff-permissions',
    path: '/users/staff-permissions',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminUsersStaffRoute = AdminUsersStaffRouteImport.update({
  id: '/users/staff',
  path: '/users/staff',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersMenusRoute = AdminUsersMenusRouteImport.update({
  id: '/users/menus',
  path: '/users/menus',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersDesignationsRoute = AdminUsersDesignationsRouteImport.update({
  id: '/users/designations',
  path: '/users/designations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersDesignationPermissionsRoute =
  AdminUsersDesignationPermissionsRouteImport.update({
    id: '/users/designation-permissions',
    path: '/users/designation-permissions',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminShippingZonesRoute = AdminShippingZonesRouteImport.update({
  id: '/shipping/zones',
  path: '/shipping/zones',
  getParentRoute: () => AdminRoute,
} as any)
const AdminShippingTrackingRoute = AdminShippingTrackingRouteImport.update({
  id: '/shipping/tracking',
  path: '/shipping/tracking',
  getParentRoute: () => AdminRoute,
} as any)
const AdminShippingShipmentsRoute = AdminShippingShipmentsRouteImport.update({
  id: '/shipping/shipments',
  path: '/shipping/shipments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminShippingRulesRoute = AdminShippingRulesRouteImport.update({
  id: '/shipping/rules',
  path: '/shipping/rules',
  getParentRoute: () => AdminRoute,
} as any)
const AdminShippingReturnPickupRoute =
  AdminShippingReturnPickupRouteImport.update({
    id: '/shipping/return-pickup',
    path: '/shipping/return-pickup',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminShippingPickupRoute = AdminShippingPickupRouteImport.update({
  id: '/shipping/pickup',
  path: '/shipping/pickup',
  getParentRoute: () => AdminRoute,
} as any)
const AdminShippingNdrRoute = AdminShippingNdrRouteImport.update({
  id: '/shipping/ndr',
  path: '/shipping/ndr',
  getParentRoute: () => AdminRoute,
} as any)
const AdminShippingLabelsRoute = AdminShippingLabelsRouteImport.update({
  id: '/shipping/labels',
  path: '/shipping/labels',
  getParentRoute: () => AdminRoute,
} as any)
const AdminShippingEtaRoute = AdminShippingEtaRouteImport.update({
  id: '/shipping/eta',
  path: '/shipping/eta',
  getParentRoute: () => AdminRoute,
} as any)
const AdminShippingCouriersRoute = AdminShippingCouriersRouteImport.update({
  id: '/shipping/couriers',
  path: '/shipping/couriers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminShippingChargesRoute = AdminShippingChargesRouteImport.update({
  id: '/shipping/charges',
  path: '/shipping/charges',
  getParentRoute: () => AdminRoute,
} as any)
const AdminShippingAwbRoute = AdminShippingAwbRouteImport.update({
  id: '/shipping/awb',
  path: '/shipping/awb',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsThemeRoute = AdminSettingsThemeRouteImport.update({
  id: '/settings/theme',
  path: '/settings/theme',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsStoreRoute = AdminSettingsStoreRouteImport.update({
  id: '/settings/store',
  path: '/settings/store',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsSmsRoute = AdminSettingsSmsRouteImport.update({
  id: '/settings/sms',
  path: '/settings/sms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsShippingRoute = AdminSettingsShippingRouteImport.update({
  id: '/settings/shipping',
  path: '/settings/shipping',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsPaymentsRoute = AdminSettingsPaymentsRouteImport.update({
  id: '/settings/payments',
  path: '/settings/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsPagesRoute = AdminSettingsPagesRouteImport.update({
  id: '/settings/pages',
  path: '/settings/pages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsNotificationsRoute =
  AdminSettingsNotificationsRouteImport.update({
    id: '/settings/notifications',
    path: '/settings/notifications',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminSettingsMaintenanceRoute =
  AdminSettingsMaintenanceRouteImport.update({
    id: '/settings/maintenance',
    path: '/settings/maintenance',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminSettingsLogsRoute = AdminSettingsLogsRouteImport.update({
  id: '/settings/logs',
  path: '/settings/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsGstRoute = AdminSettingsGstRouteImport.update({
  id: '/settings/gst',
  path: '/settings/gst',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsGeneralRoute = AdminSettingsGeneralRouteImport.update({
  id: '/settings/general',
  path: '/settings/general',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsEmailRoute = AdminSettingsEmailRouteImport.update({
  id: '/settings/email',
  path: '/settings/email',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsCurrencyRoute = AdminSettingsCurrencyRouteImport.update({
  id: '/settings/currency',
  path: '/settings/currency',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsCompanyRoute = AdminSettingsCompanyRouteImport.update({
  id: '/settings/company',
  path: '/settings/company',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsBackupRoute = AdminSettingsBackupRouteImport.update({
  id: '/settings/backup',
  path: '/settings/backup',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSchoolsClassesRoute = AdminSchoolsClassesRouteImport.update({
  id: '/schools/classes',
  path: '/schools/classes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsSalesRoute = AdminReportsSalesRouteImport.update({
  id: '/reports/sales',
  path: '/reports/sales',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRevenueRoute = AdminReportsRevenueRouteImport.update({
  id: '/reports/revenue',
  path: '/reports/revenue',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsInventoryRoute = AdminReportsInventoryRouteImport.update({
  id: '/reports/inventory',
  path: '/reports/inventory',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRefundsRoute = AdminPaymentsRefundsRouteImport.update({
  id: '/payments/refunds',
  path: '/payments/refunds',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsCodRoute = AdminPaymentsCodRouteImport.update({
  id: '/payments/cod',
  path: '/payments/cod',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersReturnsRoute = AdminOrdersReturnsRouteImport.update({
  id: '/orders/returns',
  path: '/orders/returns',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRefundsRoute = AdminOrdersRefundsRouteImport.update({
  id: '/orders/refunds',
  path: '/orders/refunds',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersProcessingRoute = AdminOrdersProcessingRouteImport.update({
  id: '/orders/processing',
  path: '/orders/processing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersExchangesRoute = AdminOrdersExchangesRouteImport.update({
  id: '/orders/exchanges',
  path: '/orders/exchanges',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersCancellationsRoute =
  AdminOrdersCancellationsRouteImport.update({
    id: '/orders/cancellations',
    path: '/orders/cancellations',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminMarketingCouponsRoute = AdminMarketingCouponsRouteImport.update({
  id: '/marketing/coupons',
  path: '/marketing/coupons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLocaleTimezonesRoute = AdminLocaleTimezonesRouteImport.update({
  id: '/locale/timezones',
  path: '/locale/timezones',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLocaleStatesRoute = AdminLocaleStatesRouteImport.update({
  id: '/locale/states',
  path: '/locale/states',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLocaleLanguagesRoute = AdminLocaleLanguagesRouteImport.update({
  id: '/locale/languages',
  path: '/locale/languages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLocaleCurrenciesRoute = AdminLocaleCurrenciesRouteImport.update({
  id: '/locale/currencies',
  path: '/locale/currencies',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLocaleCountriesRoute = AdminLocaleCountriesRouteImport.update({
  id: '/locale/countries',
  path: '/locale/countries',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLocaleCitiesRoute = AdminLocaleCitiesRouteImport.update({
  id: '/locale/cities',
  path: '/locale/cities',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventoryWarehousesRoute =
  AdminInventoryWarehousesRouteImport.update({
    id: '/inventory/warehouses',
    path: '/inventory/warehouses',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminInventoryStockRoute = AdminInventoryStockRouteImport.update({
  id: '/inventory/stock',
  path: '/inventory/stock',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventoryMultiWarehouseRoute =
  AdminInventoryMultiWarehouseRouteImport.update({
    id: '/inventory/multi-warehouse',
    path: '/inventory/multi-warehouse',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminInventoryBarcodeRoute = AdminInventoryBarcodeRouteImport.update({
  id: '/inventory/barcode',
  path: '/inventory/barcode',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIntegrationsWhatsappRoute =
  AdminIntegrationsWhatsappRouteImport.update({
    id: '/integrations/whatsapp',
    path: '/integrations/whatsapp',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminIntegrationsWebhooksRoute =
  AdminIntegrationsWebhooksRouteImport.update({
    id: '/integrations/webhooks',
    path: '/integrations/webhooks',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminIntegrationsSmsRoute = AdminIntegrationsSmsRouteImport.update({
  id: '/integrations/sms',
  path: '/integrations/sms',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIntegrationsPixelRoute = AdminIntegrationsPixelRouteImport.update({
  id: '/integrations/pixel',
  path: '/integrations/pixel',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIntegrationsPaymentRoute =
  AdminIntegrationsPaymentRouteImport.update({
    id: '/integrations/payment',
    path: '/integrations/payment',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminIntegrationsGtmRoute = AdminIntegrationsGtmRouteImport.update({
  id: '/integrations/gtm',
  path: '/integrations/gtm',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIntegrationsEmailRoute = AdminIntegrationsEmailRouteImport.update({
  id: '/integrations/email',
  path: '/integrations/email',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIntegrationsCourierRoute =
  AdminIntegrationsCourierRouteImport.update({
    id: '/integrations/courier',
    path: '/integrations/courier',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminIntegrationsAnalyticsRoute =
  AdminIntegrationsAnalyticsRouteImport.update({
    id: '/integrations/analytics',
    path: '/integrations/analytics',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminIntegrationsAccountingRoute =
  AdminIntegrationsAccountingRouteImport.update({
    id: '/integrations/accounting',
    path: '/integrations/accounting',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminDashboardProductAnalyticsRoute =
  AdminDashboardProductAnalyticsRouteImport.update({
    id: '/product-analytics',
    path: '/product-analytics',
    getParentRoute: () => AdminDashboardRoute,
  } as any)
const AdminDashboardOrderAnalysisRoute =
  AdminDashboardOrderAnalysisRouteImport.update({
    id: '/order-analysis',
    path: '/order-analysis',
    getParentRoute: () => AdminDashboardRoute,
  } as any)
const AdminCustomersWishlistRoute = AdminCustomersWishlistRouteImport.update({
  id: '/customers/wishlist',
  path: '/customers/wishlist',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersTicketsRoute = AdminCustomersTicketsRouteImport.update({
  id: '/customers/tickets',
  path: '/customers/tickets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersReviewsRoute = AdminCustomersReviewsRouteImport.update({
  id: '/customers/reviews',
  path: '/customers/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCmsFaqRoute = AdminCmsFaqRouteImport.update({
  id: '/cms/faq',
  path: '/cms/faq',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCmsBlogRoute = AdminCmsBlogRouteImport.update({
  id: '/cms/blog',
  path: '/cms/blog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCmsBannersRoute = AdminCmsBannersRouteImport.update({
  id: '/cms/banners',
  path: '/cms/banners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCatalogSuppliersRoute = AdminCatalogSuppliersRouteImport.update({
  id: '/catalog/suppliers',
  path: '/catalog/suppliers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCatalogSubjectsRoute = AdminCatalogSubjectsRouteImport.update({
  id: '/catalog/subjects',
  path: '/catalog/subjects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCatalogSubcategoriesRoute =
  AdminCatalogSubcategoriesRouteImport.update({
    id: '/catalog/subcategories',
    path: '/catalog/subcategories',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminCatalogSeriesRoute = AdminCatalogSeriesRouteImport.update({
  id: '/catalog/series',
  path: '/catalog/series',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCatalogPublishersRoute = AdminCatalogPublishersRouteImport.update({
  id: '/catalog/publishers',
  path: '/catalog/publishers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCatalogLanguagesRoute = AdminCatalogLanguagesRouteImport.update({
  id: '/catalog/languages',
  path: '/catalog/languages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCatalogGenresRoute = AdminCatalogGenresRouteImport.update({
  id: '/catalog/genres',
  path: '/catalog/genres',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCatalogFormatsRoute = AdminCatalogFormatsRouteImport.update({
  id: '/catalog/formats',
  path: '/catalog/formats',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCatalogEditionsRoute = AdminCatalogEditionsRouteImport.update({
  id: '/catalog/editions',
  path: '/catalog/editions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCatalogCategoriesRoute = AdminCatalogCategoriesRouteImport.update({
  id: '/catalog/categories',
  path: '/catalog/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCatalogBrandsRoute = AdminCatalogBrandsRouteImport.update({
  id: '/catalog/brands',
  path: '/catalog/brands',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCatalogBoardsRoute = AdminCatalogBoardsRouteImport.update({
  id: '/catalog/boards',
  path: '/catalog/boards',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCatalogAuthorsRoute = AdminCatalogAuthorsRouteImport.update({
  id: '/catalog/authors',
  path: '/catalog/authors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBunchReturnsRoute = AdminBunchReturnsRouteImport.update({
  id: '/bunch/returns',
  path: '/bunch/returns',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBunchOrdersRoute = AdminBunchOrdersRouteImport.update({
  id: '/bunch/orders',
  path: '/bunch/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBunchOrderAnalysisRoute = AdminBunchOrderAnalysisRouteImport.update({
  id: '/bunch/order-analysis',
  path: '/bunch/order-analysis',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBunchExchangesRoute = AdminBunchExchangesRouteImport.update({
  id: '/bunch/exchanges',
  path: '/bunch/exchanges',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBooksImportExportRoute = AdminBooksImportExportRouteImport.update({
  id: '/books/import-export',
  path: '/books/import-export',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBooksBulkUploadRoute = AdminBooksBulkUploadRouteImport.update({
  id: '/books/bulk-upload',
  path: '/books/bulk-upload',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBooksBulkUpdateRoute = AdminBooksBulkUpdateRouteImport.update({
  id: '/books/bulk-update',
  path: '/books/bulk-update',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsTransactionsIndexRoute =
  AdminPaymentsTransactionsIndexRouteImport.update({
    id: '/payments/transactions/',
    path: '/payments/transactions/',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/$': typeof AdminSplatRoute
  '/activity-logs': typeof AdminActivityLogsRoute
  '/dashboard': typeof AdminDashboardRouteWithChildren
  '/books/bulk-update': typeof AdminBooksBulkUpdateRoute
  '/books/bulk-upload': typeof AdminBooksBulkUploadRoute
  '/books/import-export': typeof AdminBooksImportExportRoute
  '/bunch/exchanges': typeof AdminBunchExchangesRoute
  '/bunch/order-analysis': typeof AdminBunchOrderAnalysisRoute
  '/bunch/orders': typeof AdminBunchOrdersRoute
  '/bunch/returns': typeof AdminBunchReturnsRoute
  '/catalog/authors': typeof AdminCatalogAuthorsRoute
  '/catalog/boards': typeof AdminCatalogBoardsRoute
  '/catalog/brands': typeof AdminCatalogBrandsRoute
  '/catalog/categories': typeof AdminCatalogCategoriesRoute
  '/catalog/editions': typeof AdminCatalogEditionsRoute
  '/catalog/formats': typeof AdminCatalogFormatsRoute
  '/catalog/genres': typeof AdminCatalogGenresRoute
  '/catalog/languages': typeof AdminCatalogLanguagesRoute
  '/catalog/publishers': typeof AdminCatalogPublishersRoute
  '/catalog/series': typeof AdminCatalogSeriesRoute
  '/catalog/subcategories': typeof AdminCatalogSubcategoriesRoute
  '/catalog/subjects': typeof AdminCatalogSubjectsRoute
  '/catalog/suppliers': typeof AdminCatalogSuppliersRoute
  '/cms/banners': typeof AdminCmsBannersRoute
  '/cms/blog': typeof AdminCmsBlogRoute
  '/cms/faq': typeof AdminCmsFaqRoute
  '/customers/reviews': typeof AdminCustomersReviewsRoute
  '/customers/tickets': typeof AdminCustomersTicketsRoute
  '/customers/wishlist': typeof AdminCustomersWishlistRoute
  '/dashboard/order-analysis': typeof AdminDashboardOrderAnalysisRoute
  '/dashboard/product-analytics': typeof AdminDashboardProductAnalyticsRoute
  '/integrations/accounting': typeof AdminIntegrationsAccountingRoute
  '/integrations/analytics': typeof AdminIntegrationsAnalyticsRoute
  '/integrations/courier': typeof AdminIntegrationsCourierRoute
  '/integrations/email': typeof AdminIntegrationsEmailRoute
  '/integrations/gtm': typeof AdminIntegrationsGtmRoute
  '/integrations/payment': typeof AdminIntegrationsPaymentRoute
  '/integrations/pixel': typeof AdminIntegrationsPixelRoute
  '/integrations/sms': typeof AdminIntegrationsSmsRoute
  '/integrations/webhooks': typeof AdminIntegrationsWebhooksRoute
  '/integrations/whatsapp': typeof AdminIntegrationsWhatsappRoute
  '/inventory/barcode': typeof AdminInventoryBarcodeRoute
  '/inventory/multi-warehouse': typeof AdminInventoryMultiWarehouseRoute
  '/inventory/stock': typeof AdminInventoryStockRoute
  '/inventory/warehouses': typeof AdminInventoryWarehousesRoute
  '/locale/cities': typeof AdminLocaleCitiesRoute
  '/locale/countries': typeof AdminLocaleCountriesRoute
  '/locale/currencies': typeof AdminLocaleCurrenciesRoute
  '/locale/languages': typeof AdminLocaleLanguagesRoute
  '/locale/states': typeof AdminLocaleStatesRoute
  '/locale/timezones': typeof AdminLocaleTimezonesRoute
  '/marketing/coupons': typeof AdminMarketingCouponsRoute
  '/orders/cancellations': typeof AdminOrdersCancellationsRoute
  '/orders/exchanges': typeof AdminOrdersExchangesRoute
  '/orders/processing': typeof AdminOrdersProcessingRoute
  '/orders/refunds': typeof AdminOrdersRefundsRoute
  '/orders/returns': typeof AdminOrdersReturnsRoute
  '/payments/cod': typeof AdminPaymentsCodRoute
  '/payments/refunds': typeof AdminPaymentsRefundsRoute
  '/reports/inventory': typeof AdminReportsInventoryRoute
  '/reports/revenue': typeof AdminReportsRevenueRoute
  '/reports/sales': typeof AdminReportsSalesRoute
  '/schools/classes': typeof AdminSchoolsClassesRoute
  '/settings/backup': typeof AdminSettingsBackupRoute
  '/settings/company': typeof AdminSettingsCompanyRoute
  '/settings/currency': typeof AdminSettingsCurrencyRoute
  '/settings/email': typeof AdminSettingsEmailRoute
  '/settings/general': typeof AdminSettingsGeneralRoute
  '/settings/gst': typeof AdminSettingsGstRoute
  '/settings/logs': typeof AdminSettingsLogsRoute
  '/settings/maintenance': typeof AdminSettingsMaintenanceRoute
  '/settings/notifications': typeof AdminSettingsNotificationsRoute
  '/settings/pages': typeof AdminSettingsPagesRoute
  '/settings/payments': typeof AdminSettingsPaymentsRoute
  '/settings/shipping': typeof AdminSettingsShippingRoute
  '/settings/sms': typeof AdminSettingsSmsRoute
  '/settings/store': typeof AdminSettingsStoreRoute
  '/settings/theme': typeof AdminSettingsThemeRoute
  '/shipping/awb': typeof AdminShippingAwbRoute
  '/shipping/charges': typeof AdminShippingChargesRoute
  '/shipping/couriers': typeof AdminShippingCouriersRoute
  '/shipping/eta': typeof AdminShippingEtaRoute
  '/shipping/labels': typeof AdminShippingLabelsRoute
  '/shipping/ndr': typeof AdminShippingNdrRoute
  '/shipping/pickup': typeof AdminShippingPickupRoute
  '/shipping/return-pickup': typeof AdminShippingReturnPickupRoute
  '/shipping/rules': typeof AdminShippingRulesRoute
  '/shipping/shipments': typeof AdminShippingShipmentsRoute
  '/shipping/tracking': typeof AdminShippingTrackingRoute
  '/shipping/zones': typeof AdminShippingZonesRoute
  '/users/designation-permissions': typeof AdminUsersDesignationPermissionsRoute
  '/users/designations': typeof AdminUsersDesignationsRoute
  '/users/menus': typeof AdminUsersMenusRoute
  '/users/staff': typeof AdminUsersStaffRoute
  '/users/staff-permissions': typeof AdminUsersStaffPermissionsRoute
  '/print/invoice/$id': typeof PrintInvoiceIdRoute
  '/print/label/$id': typeof PrintLabelIdRoute
  '/books/': typeof AdminBooksIndexRoute
  '/bunch/': typeof AdminBunchIndexRoute
  '/customers/': typeof AdminCustomersIndexRoute
  '/dashboard/': typeof AdminDashboardIndexRoute
  '/orders/': typeof AdminOrdersIndexRoute
  '/reports/': typeof AdminReportsIndexRoute
  '/schools/': typeof AdminSchoolsIndexRoute
  '/payments/transactions/': typeof AdminPaymentsTransactionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/$': typeof AdminSplatRoute
  '/activity-logs': typeof AdminActivityLogsRoute
  '/books/bulk-update': typeof AdminBooksBulkUpdateRoute
  '/books/bulk-upload': typeof AdminBooksBulkUploadRoute
  '/books/import-export': typeof AdminBooksImportExportRoute
  '/bunch/exchanges': typeof AdminBunchExchangesRoute
  '/bunch/order-analysis': typeof AdminBunchOrderAnalysisRoute
  '/bunch/orders': typeof AdminBunchOrdersRoute
  '/bunch/returns': typeof AdminBunchReturnsRoute
  '/catalog/authors': typeof AdminCatalogAuthorsRoute
  '/catalog/boards': typeof AdminCatalogBoardsRoute
  '/catalog/brands': typeof AdminCatalogBrandsRoute
  '/catalog/categories': typeof AdminCatalogCategoriesRoute
  '/catalog/editions': typeof AdminCatalogEditionsRoute
  '/catalog/formats': typeof AdminCatalogFormatsRoute
  '/catalog/genres': typeof AdminCatalogGenresRoute
  '/catalog/languages': typeof AdminCatalogLanguagesRoute
  '/catalog/publishers': typeof AdminCatalogPublishersRoute
  '/catalog/series': typeof AdminCatalogSeriesRoute
  '/catalog/subcategories': typeof AdminCatalogSubcategoriesRoute
  '/catalog/subjects': typeof AdminCatalogSubjectsRoute
  '/catalog/suppliers': typeof AdminCatalogSuppliersRoute
  '/cms/banners': typeof AdminCmsBannersRoute
  '/cms/blog': typeof AdminCmsBlogRoute
  '/cms/faq': typeof AdminCmsFaqRoute
  '/customers/reviews': typeof AdminCustomersReviewsRoute
  '/customers/tickets': typeof AdminCustomersTicketsRoute
  '/customers/wishlist': typeof AdminCustomersWishlistRoute
  '/dashboard/order-analysis': typeof AdminDashboardOrderAnalysisRoute
  '/dashboard/product-analytics': typeof AdminDashboardProductAnalyticsRoute
  '/integrations/accounting': typeof AdminIntegrationsAccountingRoute
  '/integrations/analytics': typeof AdminIntegrationsAnalyticsRoute
  '/integrations/courier': typeof AdminIntegrationsCourierRoute
  '/integrations/email': typeof AdminIntegrationsEmailRoute
  '/integrations/gtm': typeof AdminIntegrationsGtmRoute
  '/integrations/payment': typeof AdminIntegrationsPaymentRoute
  '/integrations/pixel': typeof AdminIntegrationsPixelRoute
  '/integrations/sms': typeof AdminIntegrationsSmsRoute
  '/integrations/webhooks': typeof AdminIntegrationsWebhooksRoute
  '/integrations/whatsapp': typeof AdminIntegrationsWhatsappRoute
  '/inventory/barcode': typeof AdminInventoryBarcodeRoute
  '/inventory/multi-warehouse': typeof AdminInventoryMultiWarehouseRoute
  '/inventory/stock': typeof AdminInventoryStockRoute
  '/inventory/warehouses': typeof AdminInventoryWarehousesRoute
  '/locale/cities': typeof AdminLocaleCitiesRoute
  '/locale/countries': typeof AdminLocaleCountriesRoute
  '/locale/currencies': typeof AdminLocaleCurrenciesRoute
  '/locale/languages': typeof AdminLocaleLanguagesRoute
  '/locale/states': typeof AdminLocaleStatesRoute
  '/locale/timezones': typeof AdminLocaleTimezonesRoute
  '/marketing/coupons': typeof AdminMarketingCouponsRoute
  '/orders/cancellations': typeof AdminOrdersCancellationsRoute
  '/orders/exchanges': typeof AdminOrdersExchangesRoute
  '/orders/processing': typeof AdminOrdersProcessingRoute
  '/orders/refunds': typeof AdminOrdersRefundsRoute
  '/orders/returns': typeof AdminOrdersReturnsRoute
  '/payments/cod': typeof AdminPaymentsCodRoute
  '/payments/refunds': typeof AdminPaymentsRefundsRoute
  '/reports/inventory': typeof AdminReportsInventoryRoute
  '/reports/revenue': typeof AdminReportsRevenueRoute
  '/reports/sales': typeof AdminReportsSalesRoute
  '/schools/classes': typeof AdminSchoolsClassesRoute
  '/settings/backup': typeof AdminSettingsBackupRoute
  '/settings/company': typeof AdminSettingsCompanyRoute
  '/settings/currency': typeof AdminSettingsCurrencyRoute
  '/settings/email': typeof AdminSettingsEmailRoute
  '/settings/general': typeof AdminSettingsGeneralRoute
  '/settings/gst': typeof AdminSettingsGstRoute
  '/settings/logs': typeof AdminSettingsLogsRoute
  '/settings/maintenance': typeof AdminSettingsMaintenanceRoute
  '/settings/notifications': typeof AdminSettingsNotificationsRoute
  '/settings/pages': typeof AdminSettingsPagesRoute
  '/settings/payments': typeof AdminSettingsPaymentsRoute
  '/settings/shipping': typeof AdminSettingsShippingRoute
  '/settings/sms': typeof AdminSettingsSmsRoute
  '/settings/store': typeof AdminSettingsStoreRoute
  '/settings/theme': typeof AdminSettingsThemeRoute
  '/shipping/awb': typeof AdminShippingAwbRoute
  '/shipping/charges': typeof AdminShippingChargesRoute
  '/shipping/couriers': typeof AdminShippingCouriersRoute
  '/shipping/eta': typeof AdminShippingEtaRoute
  '/shipping/labels': typeof AdminShippingLabelsRoute
  '/shipping/ndr': typeof AdminShippingNdrRoute
  '/shipping/pickup': typeof AdminShippingPickupRoute
  '/shipping/return-pickup': typeof AdminShippingReturnPickupRoute
  '/shipping/rules': typeof AdminShippingRulesRoute
  '/shipping/shipments': typeof AdminShippingShipmentsRoute
  '/shipping/tracking': typeof AdminShippingTrackingRoute
  '/shipping/zones': typeof AdminShippingZonesRoute
  '/users/designation-permissions': typeof AdminUsersDesignationPermissionsRoute
  '/users/designations': typeof AdminUsersDesignationsRoute
  '/users/menus': typeof AdminUsersMenusRoute
  '/users/staff': typeof AdminUsersStaffRoute
  '/users/staff-permissions': typeof AdminUsersStaffPermissionsRoute
  '/print/invoice/$id': typeof PrintInvoiceIdRoute
  '/print/label/$id': typeof PrintLabelIdRoute
  '/books': typeof AdminBooksIndexRoute
  '/bunch': typeof AdminBunchIndexRoute
  '/customers': typeof AdminCustomersIndexRoute
  '/dashboard': typeof AdminDashboardIndexRoute
  '/orders': typeof AdminOrdersIndexRoute
  '/reports': typeof AdminReportsIndexRoute
  '/schools': typeof AdminSchoolsIndexRoute
  '/payments/transactions': typeof AdminPaymentsTransactionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/_admin/$': typeof AdminSplatRoute
  '/_admin/activity-logs': typeof AdminActivityLogsRoute
  '/_admin/dashboard': typeof AdminDashboardRouteWithChildren
  '/_admin/books/bulk-update': typeof AdminBooksBulkUpdateRoute
  '/_admin/books/bulk-upload': typeof AdminBooksBulkUploadRoute
  '/_admin/books/import-export': typeof AdminBooksImportExportRoute
  '/_admin/bunch/exchanges': typeof AdminBunchExchangesRoute
  '/_admin/bunch/order-analysis': typeof AdminBunchOrderAnalysisRoute
  '/_admin/bunch/orders': typeof AdminBunchOrdersRoute
  '/_admin/bunch/returns': typeof AdminBunchReturnsRoute
  '/_admin/catalog/authors': typeof AdminCatalogAuthorsRoute
  '/_admin/catalog/boards': typeof AdminCatalogBoardsRoute
  '/_admin/catalog/brands': typeof AdminCatalogBrandsRoute
  '/_admin/catalog/categories': typeof AdminCatalogCategoriesRoute
  '/_admin/catalog/editions': typeof AdminCatalogEditionsRoute
  '/_admin/catalog/formats': typeof AdminCatalogFormatsRoute
  '/_admin/catalog/genres': typeof AdminCatalogGenresRoute
  '/_admin/catalog/languages': typeof AdminCatalogLanguagesRoute
  '/_admin/catalog/publishers': typeof AdminCatalogPublishersRoute
  '/_admin/catalog/series': typeof AdminCatalogSeriesRoute
  '/_admin/catalog/subcategories': typeof AdminCatalogSubcategoriesRoute
  '/_admin/catalog/subjects': typeof AdminCatalogSubjectsRoute
  '/_admin/catalog/suppliers': typeof AdminCatalogSuppliersRoute
  '/_admin/cms/banners': typeof AdminCmsBannersRoute
  '/_admin/cms/blog': typeof AdminCmsBlogRoute
  '/_admin/cms/faq': typeof AdminCmsFaqRoute
  '/_admin/customers/reviews': typeof AdminCustomersReviewsRoute
  '/_admin/customers/tickets': typeof AdminCustomersTicketsRoute
  '/_admin/customers/wishlist': typeof AdminCustomersWishlistRoute
  '/_admin/dashboard/order-analysis': typeof AdminDashboardOrderAnalysisRoute
  '/_admin/dashboard/product-analytics': typeof AdminDashboardProductAnalyticsRoute
  '/_admin/integrations/accounting': typeof AdminIntegrationsAccountingRoute
  '/_admin/integrations/analytics': typeof AdminIntegrationsAnalyticsRoute
  '/_admin/integrations/courier': typeof AdminIntegrationsCourierRoute
  '/_admin/integrations/email': typeof AdminIntegrationsEmailRoute
  '/_admin/integrations/gtm': typeof AdminIntegrationsGtmRoute
  '/_admin/integrations/payment': typeof AdminIntegrationsPaymentRoute
  '/_admin/integrations/pixel': typeof AdminIntegrationsPixelRoute
  '/_admin/integrations/sms': typeof AdminIntegrationsSmsRoute
  '/_admin/integrations/webhooks': typeof AdminIntegrationsWebhooksRoute
  '/_admin/integrations/whatsapp': typeof AdminIntegrationsWhatsappRoute
  '/_admin/inventory/barcode': typeof AdminInventoryBarcodeRoute
  '/_admin/inventory/multi-warehouse': typeof AdminInventoryMultiWarehouseRoute
  '/_admin/inventory/stock': typeof AdminInventoryStockRoute
  '/_admin/inventory/warehouses': typeof AdminInventoryWarehousesRoute
  '/_admin/locale/cities': typeof AdminLocaleCitiesRoute
  '/_admin/locale/countries': typeof AdminLocaleCountriesRoute
  '/_admin/locale/currencies': typeof AdminLocaleCurrenciesRoute
  '/_admin/locale/languages': typeof AdminLocaleLanguagesRoute
  '/_admin/locale/states': typeof AdminLocaleStatesRoute
  '/_admin/locale/timezones': typeof AdminLocaleTimezonesRoute
  '/_admin/marketing/coupons': typeof AdminMarketingCouponsRoute
  '/_admin/orders/cancellations': typeof AdminOrdersCancellationsRoute
  '/_admin/orders/exchanges': typeof AdminOrdersExchangesRoute
  '/_admin/orders/processing': typeof AdminOrdersProcessingRoute
  '/_admin/orders/refunds': typeof AdminOrdersRefundsRoute
  '/_admin/orders/returns': typeof AdminOrdersReturnsRoute
  '/_admin/payments/cod': typeof AdminPaymentsCodRoute
  '/_admin/payments/refunds': typeof AdminPaymentsRefundsRoute
  '/_admin/reports/inventory': typeof AdminReportsInventoryRoute
  '/_admin/reports/revenue': typeof AdminReportsRevenueRoute
  '/_admin/reports/sales': typeof AdminReportsSalesRoute
  '/_admin/schools/classes': typeof AdminSchoolsClassesRoute
  '/_admin/settings/backup': typeof AdminSettingsBackupRoute
  '/_admin/settings/company': typeof AdminSettingsCompanyRoute
  '/_admin/settings/currency': typeof AdminSettingsCurrencyRoute
  '/_admin/settings/email': typeof AdminSettingsEmailRoute
  '/_admin/settings/general': typeof AdminSettingsGeneralRoute
  '/_admin/settings/gst': typeof AdminSettingsGstRoute
  '/_admin/settings/logs': typeof AdminSettingsLogsRoute
  '/_admin/settings/maintenance': typeof AdminSettingsMaintenanceRoute
  '/_admin/settings/notifications': typeof AdminSettingsNotificationsRoute
  '/_admin/settings/pages': typeof AdminSettingsPagesRoute
  '/_admin/settings/payments': typeof AdminSettingsPaymentsRoute
  '/_admin/settings/shipping': typeof AdminSettingsShippingRoute
  '/_admin/settings/sms': typeof AdminSettingsSmsRoute
  '/_admin/settings/store': typeof AdminSettingsStoreRoute
  '/_admin/settings/theme': typeof AdminSettingsThemeRoute
  '/_admin/shipping/awb': typeof AdminShippingAwbRoute
  '/_admin/shipping/charges': typeof AdminShippingChargesRoute
  '/_admin/shipping/couriers': typeof AdminShippingCouriersRoute
  '/_admin/shipping/eta': typeof AdminShippingEtaRoute
  '/_admin/shipping/labels': typeof AdminShippingLabelsRoute
  '/_admin/shipping/ndr': typeof AdminShippingNdrRoute
  '/_admin/shipping/pickup': typeof AdminShippingPickupRoute
  '/_admin/shipping/return-pickup': typeof AdminShippingReturnPickupRoute
  '/_admin/shipping/rules': typeof AdminShippingRulesRoute
  '/_admin/shipping/shipments': typeof AdminShippingShipmentsRoute
  '/_admin/shipping/tracking': typeof AdminShippingTrackingRoute
  '/_admin/shipping/zones': typeof AdminShippingZonesRoute
  '/_admin/users/designation-permissions': typeof AdminUsersDesignationPermissionsRoute
  '/_admin/users/designations': typeof AdminUsersDesignationsRoute
  '/_admin/users/menus': typeof AdminUsersMenusRoute
  '/_admin/users/staff': typeof AdminUsersStaffRoute
  '/_admin/users/staff-permissions': typeof AdminUsersStaffPermissionsRoute
  '/print/invoice/$id': typeof PrintInvoiceIdRoute
  '/print/label/$id': typeof PrintLabelIdRoute
  '/_admin/books/': typeof AdminBooksIndexRoute
  '/_admin/bunch/': typeof AdminBunchIndexRoute
  '/_admin/customers/': typeof AdminCustomersIndexRoute
  '/_admin/dashboard/': typeof AdminDashboardIndexRoute
  '/_admin/orders/': typeof AdminOrdersIndexRoute
  '/_admin/reports/': typeof AdminReportsIndexRoute
  '/_admin/schools/': typeof AdminSchoolsIndexRoute
  '/_admin/payments/transactions/': typeof AdminPaymentsTransactionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/$'
    | '/activity-logs'
    | '/dashboard'
    | '/books/bulk-update'
    | '/books/bulk-upload'
    | '/books/import-export'
    | '/bunch/exchanges'
    | '/bunch/order-analysis'
    | '/bunch/orders'
    | '/bunch/returns'
    | '/catalog/authors'
    | '/catalog/boards'
    | '/catalog/brands'
    | '/catalog/categories'
    | '/catalog/editions'
    | '/catalog/formats'
    | '/catalog/genres'
    | '/catalog/languages'
    | '/catalog/publishers'
    | '/catalog/series'
    | '/catalog/subcategories'
    | '/catalog/subjects'
    | '/catalog/suppliers'
    | '/cms/banners'
    | '/cms/blog'
    | '/cms/faq'
    | '/customers/reviews'
    | '/customers/tickets'
    | '/customers/wishlist'
    | '/dashboard/order-analysis'
    | '/dashboard/product-analytics'
    | '/integrations/accounting'
    | '/integrations/analytics'
    | '/integrations/courier'
    | '/integrations/email'
    | '/integrations/gtm'
    | '/integrations/payment'
    | '/integrations/pixel'
    | '/integrations/sms'
    | '/integrations/webhooks'
    | '/integrations/whatsapp'
    | '/inventory/barcode'
    | '/inventory/multi-warehouse'
    | '/inventory/stock'
    | '/inventory/warehouses'
    | '/locale/cities'
    | '/locale/countries'
    | '/locale/currencies'
    | '/locale/languages'
    | '/locale/states'
    | '/locale/timezones'
    | '/marketing/coupons'
    | '/orders/cancellations'
    | '/orders/exchanges'
    | '/orders/processing'
    | '/orders/refunds'
    | '/orders/returns'
    | '/payments/cod'
    | '/payments/refunds'
    | '/reports/inventory'
    | '/reports/revenue'
    | '/reports/sales'
    | '/schools/classes'
    | '/settings/backup'
    | '/settings/company'
    | '/settings/currency'
    | '/settings/email'
    | '/settings/general'
    | '/settings/gst'
    | '/settings/logs'
    | '/settings/maintenance'
    | '/settings/notifications'
    | '/settings/pages'
    | '/settings/payments'
    | '/settings/shipping'
    | '/settings/sms'
    | '/settings/store'
    | '/settings/theme'
    | '/shipping/awb'
    | '/shipping/charges'
    | '/shipping/couriers'
    | '/shipping/eta'
    | '/shipping/labels'
    | '/shipping/ndr'
    | '/shipping/pickup'
    | '/shipping/return-pickup'
    | '/shipping/rules'
    | '/shipping/shipments'
    | '/shipping/tracking'
    | '/shipping/zones'
    | '/users/designation-permissions'
    | '/users/designations'
    | '/users/menus'
    | '/users/staff'
    | '/users/staff-permissions'
    | '/print/invoice/$id'
    | '/print/label/$id'
    | '/books/'
    | '/bunch/'
    | '/customers/'
    | '/dashboard/'
    | '/orders/'
    | '/reports/'
    | '/schools/'
    | '/payments/transactions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/$'
    | '/activity-logs'
    | '/books/bulk-update'
    | '/books/bulk-upload'
    | '/books/import-export'
    | '/bunch/exchanges'
    | '/bunch/order-analysis'
    | '/bunch/orders'
    | '/bunch/returns'
    | '/catalog/authors'
    | '/catalog/boards'
    | '/catalog/brands'
    | '/catalog/categories'
    | '/catalog/editions'
    | '/catalog/formats'
    | '/catalog/genres'
    | '/catalog/languages'
    | '/catalog/publishers'
    | '/catalog/series'
    | '/catalog/subcategories'
    | '/catalog/subjects'
    | '/catalog/suppliers'
    | '/cms/banners'
    | '/cms/blog'
    | '/cms/faq'
    | '/customers/reviews'
    | '/customers/tickets'
    | '/customers/wishlist'
    | '/dashboard/order-analysis'
    | '/dashboard/product-analytics'
    | '/integrations/accounting'
    | '/integrations/analytics'
    | '/integrations/courier'
    | '/integrations/email'
    | '/integrations/gtm'
    | '/integrations/payment'
    | '/integrations/pixel'
    | '/integrations/sms'
    | '/integrations/webhooks'
    | '/integrations/whatsapp'
    | '/inventory/barcode'
    | '/inventory/multi-warehouse'
    | '/inventory/stock'
    | '/inventory/warehouses'
    | '/locale/cities'
    | '/locale/countries'
    | '/locale/currencies'
    | '/locale/languages'
    | '/locale/states'
    | '/locale/timezones'
    | '/marketing/coupons'
    | '/orders/cancellations'
    | '/orders/exchanges'
    | '/orders/processing'
    | '/orders/refunds'
    | '/orders/returns'
    | '/payments/cod'
    | '/payments/refunds'
    | '/reports/inventory'
    | '/reports/revenue'
    | '/reports/sales'
    | '/schools/classes'
    | '/settings/backup'
    | '/settings/company'
    | '/settings/currency'
    | '/settings/email'
    | '/settings/general'
    | '/settings/gst'
    | '/settings/logs'
    | '/settings/maintenance'
    | '/settings/notifications'
    | '/settings/pages'
    | '/settings/payments'
    | '/settings/shipping'
    | '/settings/sms'
    | '/settings/store'
    | '/settings/theme'
    | '/shipping/awb'
    | '/shipping/charges'
    | '/shipping/couriers'
    | '/shipping/eta'
    | '/shipping/labels'
    | '/shipping/ndr'
    | '/shipping/pickup'
    | '/shipping/return-pickup'
    | '/shipping/rules'
    | '/shipping/shipments'
    | '/shipping/tracking'
    | '/shipping/zones'
    | '/users/designation-permissions'
    | '/users/designations'
    | '/users/menus'
    | '/users/staff'
    | '/users/staff-permissions'
    | '/print/invoice/$id'
    | '/print/label/$id'
    | '/books'
    | '/bunch'
    | '/customers'
    | '/dashboard'
    | '/orders'
    | '/reports'
    | '/schools'
    | '/payments/transactions'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/login'
    | '/_admin/$'
    | '/_admin/activity-logs'
    | '/_admin/dashboard'
    | '/_admin/books/bulk-update'
    | '/_admin/books/bulk-upload'
    | '/_admin/books/import-export'
    | '/_admin/bunch/exchanges'
    | '/_admin/bunch/order-analysis'
    | '/_admin/bunch/orders'
    | '/_admin/bunch/returns'
    | '/_admin/catalog/authors'
    | '/_admin/catalog/boards'
    | '/_admin/catalog/brands'
    | '/_admin/catalog/categories'
    | '/_admin/catalog/editions'
    | '/_admin/catalog/formats'
    | '/_admin/catalog/genres'
    | '/_admin/catalog/languages'
    | '/_admin/catalog/publishers'
    | '/_admin/catalog/series'
    | '/_admin/catalog/subcategories'
    | '/_admin/catalog/subjects'
    | '/_admin/catalog/suppliers'
    | '/_admin/cms/banners'
    | '/_admin/cms/blog'
    | '/_admin/cms/faq'
    | '/_admin/customers/reviews'
    | '/_admin/customers/tickets'
    | '/_admin/customers/wishlist'
    | '/_admin/dashboard/order-analysis'
    | '/_admin/dashboard/product-analytics'
    | '/_admin/integrations/accounting'
    | '/_admin/integrations/analytics'
    | '/_admin/integrations/courier'
    | '/_admin/integrations/email'
    | '/_admin/integrations/gtm'
    | '/_admin/integrations/payment'
    | '/_admin/integrations/pixel'
    | '/_admin/integrations/sms'
    | '/_admin/integrations/webhooks'
    | '/_admin/integrations/whatsapp'
    | '/_admin/inventory/barcode'
    | '/_admin/inventory/multi-warehouse'
    | '/_admin/inventory/stock'
    | '/_admin/inventory/warehouses'
    | '/_admin/locale/cities'
    | '/_admin/locale/countries'
    | '/_admin/locale/currencies'
    | '/_admin/locale/languages'
    | '/_admin/locale/states'
    | '/_admin/locale/timezones'
    | '/_admin/marketing/coupons'
    | '/_admin/orders/cancellations'
    | '/_admin/orders/exchanges'
    | '/_admin/orders/processing'
    | '/_admin/orders/refunds'
    | '/_admin/orders/returns'
    | '/_admin/payments/cod'
    | '/_admin/payments/refunds'
    | '/_admin/reports/inventory'
    | '/_admin/reports/revenue'
    | '/_admin/reports/sales'
    | '/_admin/schools/classes'
    | '/_admin/settings/backup'
    | '/_admin/settings/company'
    | '/_admin/settings/currency'
    | '/_admin/settings/email'
    | '/_admin/settings/general'
    | '/_admin/settings/gst'
    | '/_admin/settings/logs'
    | '/_admin/settings/maintenance'
    | '/_admin/settings/notifications'
    | '/_admin/settings/pages'
    | '/_admin/settings/payments'
    | '/_admin/settings/shipping'
    | '/_admin/settings/sms'
    | '/_admin/settings/store'
    | '/_admin/settings/theme'
    | '/_admin/shipping/awb'
    | '/_admin/shipping/charges'
    | '/_admin/shipping/couriers'
    | '/_admin/shipping/eta'
    | '/_admin/shipping/labels'
    | '/_admin/shipping/ndr'
    | '/_admin/shipping/pickup'
    | '/_admin/shipping/return-pickup'
    | '/_admin/shipping/rules'
    | '/_admin/shipping/shipments'
    | '/_admin/shipping/tracking'
    | '/_admin/shipping/zones'
    | '/_admin/users/designation-permissions'
    | '/_admin/users/designations'
    | '/_admin/users/menus'
    | '/_admin/users/staff'
    | '/_admin/users/staff-permissions'
    | '/print/invoice/$id'
    | '/print/label/$id'
    | '/_admin/books/'
    | '/_admin/bunch/'
    | '/_admin/customers/'
    | '/_admin/dashboard/'
    | '/_admin/orders/'
    | '/_admin/reports/'
    | '/_admin/schools/'
    | '/_admin/payments/transactions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  PrintInvoiceIdRoute: typeof PrintInvoiceIdRoute
  PrintLabelIdRoute: typeof PrintLabelIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/dashboard': {
      id: '/_admin/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/activity-logs': {
      id: '/_admin/activity-logs'
      path: '/activity-logs'
      fullPath: '/activity-logs'
      preLoaderRoute: typeof AdminActivityLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/$': {
      id: '/_admin/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof AdminSplatRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/schools/': {
      id: '/_admin/schools/'
      path: '/schools'
      fullPath: '/schools/'
      preLoaderRoute: typeof AdminSchoolsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/reports/': {
      id: '/_admin/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AdminReportsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/orders/': {
      id: '/_admin/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof AdminOrdersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/dashboard/': {
      id: '/_admin/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AdminDashboardIndexRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/_admin/customers/': {
      id: '/_admin/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AdminCustomersIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/bunch/': {
      id: '/_admin/bunch/'
      path: '/bunch'
      fullPath: '/bunch/'
      preLoaderRoute: typeof AdminBunchIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/books/': {
      id: '/_admin/books/'
      path: '/books'
      fullPath: '/books/'
      preLoaderRoute: typeof AdminBooksIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/print/label/$id': {
      id: '/print/label/$id'
      path: '/print/label/$id'
      fullPath: '/print/label/$id'
      preLoaderRoute: typeof PrintLabelIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/print/invoice/$id': {
      id: '/print/invoice/$id'
      path: '/print/invoice/$id'
      fullPath: '/print/invoice/$id'
      preLoaderRoute: typeof PrintInvoiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/users/staff-permissions': {
      id: '/_admin/users/staff-permissions'
      path: '/users/staff-permissions'
      fullPath: '/users/staff-permissions'
      preLoaderRoute: typeof AdminUsersStaffPermissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/users/staff': {
      id: '/_admin/users/staff'
      path: '/users/staff'
      fullPath: '/users/staff'
      preLoaderRoute: typeof AdminUsersStaffRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/users/menus': {
      id: '/_admin/users/menus'
      path: '/users/menus'
      fullPath: '/users/menus'
      preLoaderRoute: typeof AdminUsersMenusRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/users/designations': {
      id: '/_admin/users/designations'
      path: '/users/designations'
      fullPath: '/users/designations'
      preLoaderRoute: typeof AdminUsersDesignationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/users/designation-permissions': {
      id: '/_admin/users/designation-permissions'
      path: '/users/designation-permissions'
      fullPath: '/users/designation-permissions'
      preLoaderRoute: typeof AdminUsersDesignationPermissionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/shipping/zones': {
      id: '/_admin/shipping/zones'
      path: '/shipping/zones'
      fullPath: '/shipping/zones'
      preLoaderRoute: typeof AdminShippingZonesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/shipping/tracking': {
      id: '/_admin/shipping/tracking'
      path: '/shipping/tracking'
      fullPath: '/shipping/tracking'
      preLoaderRoute: typeof AdminShippingTrackingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/shipping/shipments': {
      id: '/_admin/shipping/shipments'
      path: '/shipping/shipments'
      fullPath: '/shipping/shipments'
      preLoaderRoute: typeof AdminShippingShipmentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/shipping/rules': {
      id: '/_admin/shipping/rules'
      path: '/shipping/rules'
      fullPath: '/shipping/rules'
      preLoaderRoute: typeof AdminShippingRulesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/shipping/return-pickup': {
      id: '/_admin/shipping/return-pickup'
      path: '/shipping/return-pickup'
      fullPath: '/shipping/return-pickup'
      preLoaderRoute: typeof AdminShippingReturnPickupRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/shipping/pickup': {
      id: '/_admin/shipping/pickup'
      path: '/shipping/pickup'
      fullPath: '/shipping/pickup'
      preLoaderRoute: typeof AdminShippingPickupRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/shipping/ndr': {
      id: '/_admin/shipping/ndr'
      path: '/shipping/ndr'
      fullPath: '/shipping/ndr'
      preLoaderRoute: typeof AdminShippingNdrRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/shipping/labels': {
      id: '/_admin/shipping/labels'
      path: '/shipping/labels'
      fullPath: '/shipping/labels'
      preLoaderRoute: typeof AdminShippingLabelsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/shipping/eta': {
      id: '/_admin/shipping/eta'
      path: '/shipping/eta'
      fullPath: '/shipping/eta'
      preLoaderRoute: typeof AdminShippingEtaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/shipping/couriers': {
      id: '/_admin/shipping/couriers'
      path: '/shipping/couriers'
      fullPath: '/shipping/couriers'
      preLoaderRoute: typeof AdminShippingCouriersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/shipping/charges': {
      id: '/_admin/shipping/charges'
      path: '/shipping/charges'
      fullPath: '/shipping/charges'
      preLoaderRoute: typeof AdminShippingChargesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/shipping/awb': {
      id: '/_admin/shipping/awb'
      path: '/shipping/awb'
      fullPath: '/shipping/awb'
      preLoaderRoute: typeof AdminShippingAwbRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/settings/theme': {
      id: '/_admin/settings/theme'
      path: '/settings/theme'
      fullPath: '/settings/theme'
      preLoaderRoute: typeof AdminSettingsThemeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/settings/store': {
      id: '/_admin/settings/store'
      path: '/settings/store'
      fullPath: '/settings/store'
      preLoaderRoute: typeof AdminSettingsStoreRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/settings/sms': {
      id: '/_admin/settings/sms'
      path: '/settings/sms'
      fullPath: '/settings/sms'
      preLoaderRoute: typeof AdminSettingsSmsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/settings/shipping': {
      id: '/_admin/settings/shipping'
      path: '/settings/shipping'
      fullPath: '/settings/shipping'
      preLoaderRoute: typeof AdminSettingsShippingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/settings/payments': {
      id: '/_admin/settings/payments'
      path: '/settings/payments'
      fullPath: '/settings/payments'
      preLoaderRoute: typeof AdminSettingsPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/settings/pages': {
      id: '/_admin/settings/pages'
      path: '/settings/pages'
      fullPath: '/settings/pages'
      preLoaderRoute: typeof AdminSettingsPagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/settings/notifications': {
      id: '/_admin/settings/notifications'
      path: '/settings/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AdminSettingsNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/settings/maintenance': {
      id: '/_admin/settings/maintenance'
      path: '/settings/maintenance'
      fullPath: '/settings/maintenance'
      preLoaderRoute: typeof AdminSettingsMaintenanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/settings/logs': {
      id: '/_admin/settings/logs'
      path: '/settings/logs'
      fullPath: '/settings/logs'
      preLoaderRoute: typeof AdminSettingsLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/settings/gst': {
      id: '/_admin/settings/gst'
      path: '/settings/gst'
      fullPath: '/settings/gst'
      preLoaderRoute: typeof AdminSettingsGstRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/settings/general': {
      id: '/_admin/settings/general'
      path: '/settings/general'
      fullPath: '/settings/general'
      preLoaderRoute: typeof AdminSettingsGeneralRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/settings/email': {
      id: '/_admin/settings/email'
      path: '/settings/email'
      fullPath: '/settings/email'
      preLoaderRoute: typeof AdminSettingsEmailRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/settings/currency': {
      id: '/_admin/settings/currency'
      path: '/settings/currency'
      fullPath: '/settings/currency'
      preLoaderRoute: typeof AdminSettingsCurrencyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/settings/company': {
      id: '/_admin/settings/company'
      path: '/settings/company'
      fullPath: '/settings/company'
      preLoaderRoute: typeof AdminSettingsCompanyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/settings/backup': {
      id: '/_admin/settings/backup'
      path: '/settings/backup'
      fullPath: '/settings/backup'
      preLoaderRoute: typeof AdminSettingsBackupRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/schools/classes': {
      id: '/_admin/schools/classes'
      path: '/schools/classes'
      fullPath: '/schools/classes'
      preLoaderRoute: typeof AdminSchoolsClassesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/reports/sales': {
      id: '/_admin/reports/sales'
      path: '/reports/sales'
      fullPath: '/reports/sales'
      preLoaderRoute: typeof AdminReportsSalesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/reports/revenue': {
      id: '/_admin/reports/revenue'
      path: '/reports/revenue'
      fullPath: '/reports/revenue'
      preLoaderRoute: typeof AdminReportsRevenueRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/reports/inventory': {
      id: '/_admin/reports/inventory'
      path: '/reports/inventory'
      fullPath: '/reports/inventory'
      preLoaderRoute: typeof AdminReportsInventoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/payments/refunds': {
      id: '/_admin/payments/refunds'
      path: '/payments/refunds'
      fullPath: '/payments/refunds'
      preLoaderRoute: typeof AdminPaymentsRefundsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/payments/cod': {
      id: '/_admin/payments/cod'
      path: '/payments/cod'
      fullPath: '/payments/cod'
      preLoaderRoute: typeof AdminPaymentsCodRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/orders/returns': {
      id: '/_admin/orders/returns'
      path: '/orders/returns'
      fullPath: '/orders/returns'
      preLoaderRoute: typeof AdminOrdersReturnsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/orders/refunds': {
      id: '/_admin/orders/refunds'
      path: '/orders/refunds'
      fullPath: '/orders/refunds'
      preLoaderRoute: typeof AdminOrdersRefundsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/orders/processing': {
      id: '/_admin/orders/processing'
      path: '/orders/processing'
      fullPath: '/orders/processing'
      preLoaderRoute: typeof AdminOrdersProcessingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/orders/exchanges': {
      id: '/_admin/orders/exchanges'
      path: '/orders/exchanges'
      fullPath: '/orders/exchanges'
      preLoaderRoute: typeof AdminOrdersExchangesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/orders/cancellations': {
      id: '/_admin/orders/cancellations'
      path: '/orders/cancellations'
      fullPath: '/orders/cancellations'
      preLoaderRoute: typeof AdminOrdersCancellationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/marketing/coupons': {
      id: '/_admin/marketing/coupons'
      path: '/marketing/coupons'
      fullPath: '/marketing/coupons'
      preLoaderRoute: typeof AdminMarketingCouponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/locale/timezones': {
      id: '/_admin/locale/timezones'
      path: '/locale/timezones'
      fullPath: '/locale/timezones'
      preLoaderRoute: typeof AdminLocaleTimezonesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/locale/states': {
      id: '/_admin/locale/states'
      path: '/locale/states'
      fullPath: '/locale/states'
      preLoaderRoute: typeof AdminLocaleStatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/locale/languages': {
      id: '/_admin/locale/languages'
      path: '/locale/languages'
      fullPath: '/locale/languages'
      preLoaderRoute: typeof AdminLocaleLanguagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/locale/currencies': {
      id: '/_admin/locale/currencies'
      path: '/locale/currencies'
      fullPath: '/locale/currencies'
      preLoaderRoute: typeof AdminLocaleCurrenciesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/locale/countries': {
      id: '/_admin/locale/countries'
      path: '/locale/countries'
      fullPath: '/locale/countries'
      preLoaderRoute: typeof AdminLocaleCountriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/locale/cities': {
      id: '/_admin/locale/cities'
      path: '/locale/cities'
      fullPath: '/locale/cities'
      preLoaderRoute: typeof AdminLocaleCitiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/inventory/warehouses': {
      id: '/_admin/inventory/warehouses'
      path: '/inventory/warehouses'
      fullPath: '/inventory/warehouses'
      preLoaderRoute: typeof AdminInventoryWarehousesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/inventory/stock': {
      id: '/_admin/inventory/stock'
      path: '/inventory/stock'
      fullPath: '/inventory/stock'
      preLoaderRoute: typeof AdminInventoryStockRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/inventory/multi-warehouse': {
      id: '/_admin/inventory/multi-warehouse'
      path: '/inventory/multi-warehouse'
      fullPath: '/inventory/multi-warehouse'
      preLoaderRoute: typeof AdminInventoryMultiWarehouseRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/inventory/barcode': {
      id: '/_admin/inventory/barcode'
      path: '/inventory/barcode'
      fullPath: '/inventory/barcode'
      preLoaderRoute: typeof AdminInventoryBarcodeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/integrations/whatsapp': {
      id: '/_admin/integrations/whatsapp'
      path: '/integrations/whatsapp'
      fullPath: '/integrations/whatsapp'
      preLoaderRoute: typeof AdminIntegrationsWhatsappRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/integrations/webhooks': {
      id: '/_admin/integrations/webhooks'
      path: '/integrations/webhooks'
      fullPath: '/integrations/webhooks'
      preLoaderRoute: typeof AdminIntegrationsWebhooksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/integrations/sms': {
      id: '/_admin/integrations/sms'
      path: '/integrations/sms'
      fullPath: '/integrations/sms'
      preLoaderRoute: typeof AdminIntegrationsSmsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/integrations/pixel': {
      id: '/_admin/integrations/pixel'
      path: '/integrations/pixel'
      fullPath: '/integrations/pixel'
      preLoaderRoute: typeof AdminIntegrationsPixelRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/integrations/payment': {
      id: '/_admin/integrations/payment'
      path: '/integrations/payment'
      fullPath: '/integrations/payment'
      preLoaderRoute: typeof AdminIntegrationsPaymentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/integrations/gtm': {
      id: '/_admin/integrations/gtm'
      path: '/integrations/gtm'
      fullPath: '/integrations/gtm'
      preLoaderRoute: typeof AdminIntegrationsGtmRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/integrations/email': {
      id: '/_admin/integrations/email'
      path: '/integrations/email'
      fullPath: '/integrations/email'
      preLoaderRoute: typeof AdminIntegrationsEmailRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/integrations/courier': {
      id: '/_admin/integrations/courier'
      path: '/integrations/courier'
      fullPath: '/integrations/courier'
      preLoaderRoute: typeof AdminIntegrationsCourierRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/integrations/analytics': {
      id: '/_admin/integrations/analytics'
      path: '/integrations/analytics'
      fullPath: '/integrations/analytics'
      preLoaderRoute: typeof AdminIntegrationsAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/integrations/accounting': {
      id: '/_admin/integrations/accounting'
      path: '/integrations/accounting'
      fullPath: '/integrations/accounting'
      preLoaderRoute: typeof AdminIntegrationsAccountingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/dashboard/product-analytics': {
      id: '/_admin/dashboard/product-analytics'
      path: '/product-analytics'
      fullPath: '/dashboard/product-analytics'
      preLoaderRoute: typeof AdminDashboardProductAnalyticsRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/_admin/dashboard/order-analysis': {
      id: '/_admin/dashboard/order-analysis'
      path: '/order-analysis'
      fullPath: '/dashboard/order-analysis'
      preLoaderRoute: typeof AdminDashboardOrderAnalysisRouteImport
      parentRoute: typeof AdminDashboardRoute
    }
    '/_admin/customers/wishlist': {
      id: '/_admin/customers/wishlist'
      path: '/customers/wishlist'
      fullPath: '/customers/wishlist'
      preLoaderRoute: typeof AdminCustomersWishlistRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/customers/tickets': {
      id: '/_admin/customers/tickets'
      path: '/customers/tickets'
      fullPath: '/customers/tickets'
      preLoaderRoute: typeof AdminCustomersTicketsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/customers/reviews': {
      id: '/_admin/customers/reviews'
      path: '/customers/reviews'
      fullPath: '/customers/reviews'
      preLoaderRoute: typeof AdminCustomersReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/cms/faq': {
      id: '/_admin/cms/faq'
      path: '/cms/faq'
      fullPath: '/cms/faq'
      preLoaderRoute: typeof AdminCmsFaqRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/cms/blog': {
      id: '/_admin/cms/blog'
      path: '/cms/blog'
      fullPath: '/cms/blog'
      preLoaderRoute: typeof AdminCmsBlogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/cms/banners': {
      id: '/_admin/cms/banners'
      path: '/cms/banners'
      fullPath: '/cms/banners'
      preLoaderRoute: typeof AdminCmsBannersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/catalog/suppliers': {
      id: '/_admin/catalog/suppliers'
      path: '/catalog/suppliers'
      fullPath: '/catalog/suppliers'
      preLoaderRoute: typeof AdminCatalogSuppliersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/catalog/subjects': {
      id: '/_admin/catalog/subjects'
      path: '/catalog/subjects'
      fullPath: '/catalog/subjects'
      preLoaderRoute: typeof AdminCatalogSubjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/catalog/subcategories': {
      id: '/_admin/catalog/subcategories'
      path: '/catalog/subcategories'
      fullPath: '/catalog/subcategories'
      preLoaderRoute: typeof AdminCatalogSubcategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/catalog/series': {
      id: '/_admin/catalog/series'
      path: '/catalog/series'
      fullPath: '/catalog/series'
      preLoaderRoute: typeof AdminCatalogSeriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/catalog/publishers': {
      id: '/_admin/catalog/publishers'
      path: '/catalog/publishers'
      fullPath: '/catalog/publishers'
      preLoaderRoute: typeof AdminCatalogPublishersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/catalog/languages': {
      id: '/_admin/catalog/languages'
      path: '/catalog/languages'
      fullPath: '/catalog/languages'
      preLoaderRoute: typeof AdminCatalogLanguagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/catalog/genres': {
      id: '/_admin/catalog/genres'
      path: '/catalog/genres'
      fullPath: '/catalog/genres'
      preLoaderRoute: typeof AdminCatalogGenresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/catalog/formats': {
      id: '/_admin/catalog/formats'
      path: '/catalog/formats'
      fullPath: '/catalog/formats'
      preLoaderRoute: typeof AdminCatalogFormatsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/catalog/editions': {
      id: '/_admin/catalog/editions'
      path: '/catalog/editions'
      fullPath: '/catalog/editions'
      preLoaderRoute: typeof AdminCatalogEditionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/catalog/categories': {
      id: '/_admin/catalog/categories'
      path: '/catalog/categories'
      fullPath: '/catalog/categories'
      preLoaderRoute: typeof AdminCatalogCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/catalog/brands': {
      id: '/_admin/catalog/brands'
      path: '/catalog/brands'
      fullPath: '/catalog/brands'
      preLoaderRoute: typeof AdminCatalogBrandsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/catalog/boards': {
      id: '/_admin/catalog/boards'
      path: '/catalog/boards'
      fullPath: '/catalog/boards'
      preLoaderRoute: typeof AdminCatalogBoardsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/catalog/authors': {
      id: '/_admin/catalog/authors'
      path: '/catalog/authors'
      fullPath: '/catalog/authors'
      preLoaderRoute: typeof AdminCatalogAuthorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/bunch/returns': {
      id: '/_admin/bunch/returns'
      path: '/bunch/returns'
      fullPath: '/bunch/returns'
      preLoaderRoute: typeof AdminBunchReturnsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/bunch/orders': {
      id: '/_admin/bunch/orders'
      path: '/bunch/orders'
      fullPath: '/bunch/orders'
      preLoaderRoute: typeof AdminBunchOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/bunch/order-analysis': {
      id: '/_admin/bunch/order-analysis'
      path: '/bunch/order-analysis'
      fullPath: '/bunch/order-analysis'
      preLoaderRoute: typeof AdminBunchOrderAnalysisRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/bunch/exchanges': {
      id: '/_admin/bunch/exchanges'
      path: '/bunch/exchanges'
      fullPath: '/bunch/exchanges'
      preLoaderRoute: typeof AdminBunchExchangesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/books/import-export': {
      id: '/_admin/books/import-export'
      path: '/books/import-export'
      fullPath: '/books/import-export'
      preLoaderRoute: typeof AdminBooksImportExportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/books/bulk-upload': {
      id: '/_admin/books/bulk-upload'
      path: '/books/bulk-upload'
      fullPath: '/books/bulk-upload'
      preLoaderRoute: typeof AdminBooksBulkUploadRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/books/bulk-update': {
      id: '/_admin/books/bulk-update'
      path: '/books/bulk-update'
      fullPath: '/books/bulk-update'
      preLoaderRoute: typeof AdminBooksBulkUpdateRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/payments/transactions/': {
      id: '/_admin/payments/transactions/'
      path: '/payments/transactions'
      fullPath: '/payments/transactions/'
      preLoaderRoute: typeof AdminPaymentsTransactionsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminDashboardRouteChildren {
  AdminDashboardOrderAnalysisRoute: typeof AdminDashboardOrderAnalysisRoute
  AdminDashboardProductAnalyticsRoute: typeof AdminDashboardProductAnalyticsRoute
  AdminDashboardIndexRoute: typeof AdminDashboardIndexRoute
}

const AdminDashboardRouteChildren: AdminDashboardRouteChildren = {
  AdminDashboardOrderAnalysisRoute: AdminDashboardOrderAnalysisRoute,
  AdminDashboardProductAnalyticsRoute: AdminDashboardProductAnalyticsRoute,
  AdminDashboardIndexRoute: AdminDashboardIndexRoute,
}

const AdminDashboardRouteWithChildren = AdminDashboardRoute._addFileChildren(
  AdminDashboardRouteChildren,
)

interface AdminRouteChildren {
  AdminSplatRoute: typeof AdminSplatRoute
  AdminActivityLogsRoute: typeof AdminActivityLogsRoute
  AdminDashboardRoute: typeof AdminDashboardRouteWithChildren
  AdminBooksBulkUpdateRoute: typeof AdminBooksBulkUpdateRoute
  AdminBooksBulkUploadRoute: typeof AdminBooksBulkUploadRoute
  AdminBooksImportExportRoute: typeof AdminBooksImportExportRoute
  AdminBunchExchangesRoute: typeof AdminBunchExchangesRoute
  AdminBunchOrderAnalysisRoute: typeof AdminBunchOrderAnalysisRoute
  AdminBunchOrdersRoute: typeof AdminBunchOrdersRoute
  AdminBunchReturnsRoute: typeof AdminBunchReturnsRoute
  AdminCatalogAuthorsRoute: typeof AdminCatalogAuthorsRoute
  AdminCatalogBoardsRoute: typeof AdminCatalogBoardsRoute
  AdminCatalogBrandsRoute: typeof AdminCatalogBrandsRoute
  AdminCatalogCategoriesRoute: typeof AdminCatalogCategoriesRoute
  AdminCatalogEditionsRoute: typeof AdminCatalogEditionsRoute
  AdminCatalogFormatsRoute: typeof AdminCatalogFormatsRoute
  AdminCatalogGenresRoute: typeof AdminCatalogGenresRoute
  AdminCatalogLanguagesRoute: typeof AdminCatalogLanguagesRoute
  AdminCatalogPublishersRoute: typeof AdminCatalogPublishersRoute
  AdminCatalogSeriesRoute: typeof AdminCatalogSeriesRoute
  AdminCatalogSubcategoriesRoute: typeof AdminCatalogSubcategoriesRoute
  AdminCatalogSubjectsRoute: typeof AdminCatalogSubjectsRoute
  AdminCatalogSuppliersRoute: typeof AdminCatalogSuppliersRoute
  AdminCmsBannersRoute: typeof AdminCmsBannersRoute
  AdminCmsBlogRoute: typeof AdminCmsBlogRoute
  AdminCmsFaqRoute: typeof AdminCmsFaqRoute
  AdminCustomersReviewsRoute: typeof AdminCustomersReviewsRoute
  AdminCustomersTicketsRoute: typeof AdminCustomersTicketsRoute
  AdminCustomersWishlistRoute: typeof AdminCustomersWishlistRoute
  AdminIntegrationsAccountingRoute: typeof AdminIntegrationsAccountingRoute
  AdminIntegrationsAnalyticsRoute: typeof AdminIntegrationsAnalyticsRoute
  AdminIntegrationsCourierRoute: typeof AdminIntegrationsCourierRoute
  AdminIntegrationsEmailRoute: typeof AdminIntegrationsEmailRoute
  AdminIntegrationsGtmRoute: typeof AdminIntegrationsGtmRoute
  AdminIntegrationsPaymentRoute: typeof AdminIntegrationsPaymentRoute
  AdminIntegrationsPixelRoute: typeof AdminIntegrationsPixelRoute
  AdminIntegrationsSmsRoute: typeof AdminIntegrationsSmsRoute
  AdminIntegrationsWebhooksRoute: typeof AdminIntegrationsWebhooksRoute
  AdminIntegrationsWhatsappRoute: typeof AdminIntegrationsWhatsappRoute
  AdminInventoryBarcodeRoute: typeof AdminInventoryBarcodeRoute
  AdminInventoryMultiWarehouseRoute: typeof AdminInventoryMultiWarehouseRoute
  AdminInventoryStockRoute: typeof AdminInventoryStockRoute
  AdminInventoryWarehousesRoute: typeof AdminInventoryWarehousesRoute
  AdminLocaleCitiesRoute: typeof AdminLocaleCitiesRoute
  AdminLocaleCountriesRoute: typeof AdminLocaleCountriesRoute
  AdminLocaleCurrenciesRoute: typeof AdminLocaleCurrenciesRoute
  AdminLocaleLanguagesRoute: typeof AdminLocaleLanguagesRoute
  AdminLocaleStatesRoute: typeof AdminLocaleStatesRoute
  AdminLocaleTimezonesRoute: typeof AdminLocaleTimezonesRoute
  AdminMarketingCouponsRoute: typeof AdminMarketingCouponsRoute
  AdminOrdersCancellationsRoute: typeof AdminOrdersCancellationsRoute
  AdminOrdersExchangesRoute: typeof AdminOrdersExchangesRoute
  AdminOrdersProcessingRoute: typeof AdminOrdersProcessingRoute
  AdminOrdersRefundsRoute: typeof AdminOrdersRefundsRoute
  AdminOrdersReturnsRoute: typeof AdminOrdersReturnsRoute
  AdminPaymentsCodRoute: typeof AdminPaymentsCodRoute
  AdminPaymentsRefundsRoute: typeof AdminPaymentsRefundsRoute
  AdminReportsInventoryRoute: typeof AdminReportsInventoryRoute
  AdminReportsRevenueRoute: typeof AdminReportsRevenueRoute
  AdminReportsSalesRoute: typeof AdminReportsSalesRoute
  AdminSchoolsClassesRoute: typeof AdminSchoolsClassesRoute
  AdminSettingsBackupRoute: typeof AdminSettingsBackupRoute
  AdminSettingsCompanyRoute: typeof AdminSettingsCompanyRoute
  AdminSettingsCurrencyRoute: typeof AdminSettingsCurrencyRoute
  AdminSettingsEmailRoute: typeof AdminSettingsEmailRoute
  AdminSettingsGeneralRoute: typeof AdminSettingsGeneralRoute
  AdminSettingsGstRoute: typeof AdminSettingsGstRoute
  AdminSettingsLogsRoute: typeof AdminSettingsLogsRoute
  AdminSettingsMaintenanceRoute: typeof AdminSettingsMaintenanceRoute
  AdminSettingsNotificationsRoute: typeof AdminSettingsNotificationsRoute
  AdminSettingsPagesRoute: typeof AdminSettingsPagesRoute
  AdminSettingsPaymentsRoute: typeof AdminSettingsPaymentsRoute
  AdminSettingsShippingRoute: typeof AdminSettingsShippingRoute
  AdminSettingsSmsRoute: typeof AdminSettingsSmsRoute
  AdminSettingsStoreRoute: typeof AdminSettingsStoreRoute
  AdminSettingsThemeRoute: typeof AdminSettingsThemeRoute
  AdminShippingAwbRoute: typeof AdminShippingAwbRoute
  AdminShippingChargesRoute: typeof AdminShippingChargesRoute
  AdminShippingCouriersRoute: typeof AdminShippingCouriersRoute
  AdminShippingEtaRoute: typeof AdminShippingEtaRoute
  AdminShippingLabelsRoute: typeof AdminShippingLabelsRoute
  AdminShippingNdrRoute: typeof AdminShippingNdrRoute
  AdminShippingPickupRoute: typeof AdminShippingPickupRoute
  AdminShippingReturnPickupRoute: typeof AdminShippingReturnPickupRoute
  AdminShippingRulesRoute: typeof AdminShippingRulesRoute
  AdminShippingShipmentsRoute: typeof AdminShippingShipmentsRoute
  AdminShippingTrackingRoute: typeof AdminShippingTrackingRoute
  AdminShippingZonesRoute: typeof AdminShippingZonesRoute
  AdminUsersDesignationPermissionsRoute: typeof AdminUsersDesignationPermissionsRoute
  AdminUsersDesignationsRoute: typeof AdminUsersDesignationsRoute
  AdminUsersMenusRoute: typeof AdminUsersMenusRoute
  AdminUsersStaffRoute: typeof AdminUsersStaffRoute
  AdminUsersStaffPermissionsRoute: typeof AdminUsersStaffPermissionsRoute
  AdminBooksIndexRoute: typeof AdminBooksIndexRoute
  AdminBunchIndexRoute: typeof AdminBunchIndexRoute
  AdminCustomersIndexRoute: typeof AdminCustomersIndexRoute
  AdminOrdersIndexRoute: typeof AdminOrdersIndexRoute
  AdminReportsIndexRoute: typeof AdminReportsIndexRoute
  AdminSchoolsIndexRoute: typeof AdminSchoolsIndexRoute
  AdminPaymentsTransactionsIndexRoute: typeof AdminPaymentsTransactionsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminSplatRoute: AdminSplatRoute,
  AdminActivityLogsRoute: AdminActivityLogsRoute,
  AdminDashboardRoute: AdminDashboardRouteWithChildren,
  AdminBooksBulkUpdateRoute: AdminBooksBulkUpdateRoute,
  AdminBooksBulkUploadRoute: AdminBooksBulkUploadRoute,
  AdminBooksImportExportRoute: AdminBooksImportExportRoute,
  AdminBunchExchangesRoute: AdminBunchExchangesRoute,
  AdminBunchOrderAnalysisRoute: AdminBunchOrderAnalysisRoute,
  AdminBunchOrdersRoute: AdminBunchOrdersRoute,
  AdminBunchReturnsRoute: AdminBunchReturnsRoute,
  AdminCatalogAuthorsRoute: AdminCatalogAuthorsRoute,
  AdminCatalogBoardsRoute: AdminCatalogBoardsRoute,
  AdminCatalogBrandsRoute: AdminCatalogBrandsRoute,
  AdminCatalogCategoriesRoute: AdminCatalogCategoriesRoute,
  AdminCatalogEditionsRoute: AdminCatalogEditionsRoute,
  AdminCatalogFormatsRoute: AdminCatalogFormatsRoute,
  AdminCatalogGenresRoute: AdminCatalogGenresRoute,
  AdminCatalogLanguagesRoute: AdminCatalogLanguagesRoute,
  AdminCatalogPublishersRoute: AdminCatalogPublishersRoute,
  AdminCatalogSeriesRoute: AdminCatalogSeriesRoute,
  AdminCatalogSubcategoriesRoute: AdminCatalogSubcategoriesRoute,
  AdminCatalogSubjectsRoute: AdminCatalogSubjectsRoute,
  AdminCatalogSuppliersRoute: AdminCatalogSuppliersRoute,
  AdminCmsBannersRoute: AdminCmsBannersRoute,
  AdminCmsBlogRoute: AdminCmsBlogRoute,
  AdminCmsFaqRoute: AdminCmsFaqRoute,
  AdminCustomersReviewsRoute: AdminCustomersReviewsRoute,
  AdminCustomersTicketsRoute: AdminCustomersTicketsRoute,
  AdminCustomersWishlistRoute: AdminCustomersWishlistRoute,
  AdminIntegrationsAccountingRoute: AdminIntegrationsAccountingRoute,
  AdminIntegrationsAnalyticsRoute: AdminIntegrationsAnalyticsRoute,
  AdminIntegrationsCourierRoute: AdminIntegrationsCourierRoute,
  AdminIntegrationsEmailRoute: AdminIntegrationsEmailRoute,
  AdminIntegrationsGtmRoute: AdminIntegrationsGtmRoute,
  AdminIntegrationsPaymentRoute: AdminIntegrationsPaymentRoute,
  AdminIntegrationsPixelRoute: AdminIntegrationsPixelRoute,
  AdminIntegrationsSmsRoute: AdminIntegrationsSmsRoute,
  AdminIntegrationsWebhooksRoute: AdminIntegrationsWebhooksRoute,
  AdminIntegrationsWhatsappRoute: AdminIntegrationsWhatsappRoute,
  AdminInventoryBarcodeRoute: AdminInventoryBarcodeRoute,
  AdminInventoryMultiWarehouseRoute: AdminInventoryMultiWarehouseRoute,
  AdminInventoryStockRoute: AdminInventoryStockRoute,
  AdminInventoryWarehousesRoute: AdminInventoryWarehousesRoute,
  AdminLocaleCitiesRoute: AdminLocaleCitiesRoute,
  AdminLocaleCountriesRoute: AdminLocaleCountriesRoute,
  AdminLocaleCurrenciesRoute: AdminLocaleCurrenciesRoute,
  AdminLocaleLanguagesRoute: AdminLocaleLanguagesRoute,
  AdminLocaleStatesRoute: AdminLocaleStatesRoute,
  AdminLocaleTimezonesRoute: AdminLocaleTimezonesRoute,
  AdminMarketingCouponsRoute: AdminMarketingCouponsRoute,
  AdminOrdersCancellationsRoute: AdminOrdersCancellationsRoute,
  AdminOrdersExchangesRoute: AdminOrdersExchangesRoute,
  AdminOrdersProcessingRoute: AdminOrdersProcessingRoute,
  AdminOrdersRefundsRoute: AdminOrdersRefundsRoute,
  AdminOrdersReturnsRoute: AdminOrdersReturnsRoute,
  AdminPaymentsCodRoute: AdminPaymentsCodRoute,
  AdminPaymentsRefundsRoute: AdminPaymentsRefundsRoute,
  AdminReportsInventoryRoute: AdminReportsInventoryRoute,
  AdminReportsRevenueRoute: AdminReportsRevenueRoute,
  AdminReportsSalesRoute: AdminReportsSalesRoute,
  AdminSchoolsClassesRoute: AdminSchoolsClassesRoute,
  AdminSettingsBackupRoute: AdminSettingsBackupRoute,
  AdminSettingsCompanyRoute: AdminSettingsCompanyRoute,
  AdminSettingsCurrencyRoute: AdminSettingsCurrencyRoute,
  AdminSettingsEmailRoute: AdminSettingsEmailRoute,
  AdminSettingsGeneralRoute: AdminSettingsGeneralRoute,
  AdminSettingsGstRoute: AdminSettingsGstRoute,
  AdminSettingsLogsRoute: AdminSettingsLogsRoute,
  AdminSettingsMaintenanceRoute: AdminSettingsMaintenanceRoute,
  AdminSettingsNotificationsRoute: AdminSettingsNotificationsRoute,
  AdminSettingsPagesRoute: AdminSettingsPagesRoute,
  AdminSettingsPaymentsRoute: AdminSettingsPaymentsRoute,
  AdminSettingsShippingRoute: AdminSettingsShippingRoute,
  AdminSettingsSmsRoute: AdminSettingsSmsRoute,
  AdminSettingsStoreRoute: AdminSettingsStoreRoute,
  AdminSettingsThemeRoute: AdminSettingsThemeRoute,
  AdminShippingAwbRoute: AdminShippingAwbRoute,
  AdminShippingChargesRoute: AdminShippingChargesRoute,
  AdminShippingCouriersRoute: AdminShippingCouriersRoute,
  AdminShippingEtaRoute: AdminShippingEtaRoute,
  AdminShippingLabelsRoute: AdminShippingLabelsRoute,
  AdminShippingNdrRoute: AdminShippingNdrRoute,
  AdminShippingPickupRoute: AdminShippingPickupRoute,
  AdminShippingReturnPickupRoute: AdminShippingReturnPickupRoute,
  AdminShippingRulesRoute: AdminShippingRulesRoute,
  AdminShippingShipmentsRoute: AdminShippingShipmentsRoute,
  AdminShippingTrackingRoute: AdminShippingTrackingRoute,
  AdminShippingZonesRoute: AdminShippingZonesRoute,
  AdminUsersDesignationPermissionsRoute: AdminUsersDesignationPermissionsRoute,
  AdminUsersDesignationsRoute: AdminUsersDesignationsRoute,
  AdminUsersMenusRoute: AdminUsersMenusRoute,
  AdminUsersStaffRoute: AdminUsersStaffRoute,
  AdminUsersStaffPermissionsRoute: AdminUsersStaffPermissionsRoute,
  AdminBooksIndexRoute: AdminBooksIndexRoute,
  AdminBunchIndexRoute: AdminBunchIndexRoute,
  AdminCustomersIndexRoute: AdminCustomersIndexRoute,
  AdminOrdersIndexRoute: AdminOrdersIndexRoute,
  AdminReportsIndexRoute: AdminReportsIndexRoute,
  AdminSchoolsIndexRoute: AdminSchoolsIndexRoute,
  AdminPaymentsTransactionsIndexRoute: AdminPaymentsTransactionsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  PrintInvoiceIdRoute: PrintInvoiceIdRoute,
  PrintLabelIdRoute: PrintLabelIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
